#define UNICODE_SELECTED_MODES UC_MAC, UC_WINC
#define UNICODE_KEY_MAC  KC_RALT
#define PERMISSIVE_HOLD
#define TAPPING_TERM 200
#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 12
#define DEBOUNCE 5
